package com.mori.crawler.category;

import static com.mori.crawler.category.CategoryGroup.*;

public enum NoticeCategory {
    // 국민대
    UNIVERSITY_ACADEMIC(UNIVERSITY_CATEGORY, "대학 학사공지"),
    UNIVERSITY_SCHOLARSHIP(UNIVERSITY_CATEGORY, "대학 장학공지"),
    UNIVERSITY_SPECIALLECTURE(UNIVERSITY_CATEGORY, "대학 특강공지"),
    UNIVERSITY_CONTESTEVENT(UNIVERSITY_CATEGORY, "대학 공모행사공지"),
    UNIVERSITY_BUKAKPOLITICALFORUM(UNIVERSITY_CATEGORY, "북악정치포럼 학사공지"),
    UNIVERSITY_THURSDAYLECTURE(UNIVERSITY_CATEGORY, "목요특강 학사공지"),

    // 소프트웨어융합대학
    COMPUTERSCIENCE_ACADEMIC_RSS(COMPUTERSCIENCE_CATEGORY, "소융대 학사공지"),
    SOFTWARECENTERED_ACADEMIC(COMPUTERSCIENCE_CATEGORY, "SW중심대학사업단 학사공지"),

    // 경영대학
    BUSINESSADMINISTRATION_ACADEMIC_RSS(BUSINESSADMINISTRATION_CATEGORY, "경영대 학사공지"),

    // 건축대학
    ARCHITECTURE_ACADEMIC(ARCHITECTURE_CATEGORY, "건축대 학사공지"),

    // 사회과학대학
    SOCIALSCIENCE_ACADEMIC(SOCIALSCIENCE_CATEGORY, "사회과학대학 학사공지"),
    SOCIALSCIENCE_PUBLICADMINISTRATION_ACADEMIC(SOCIALSCIENCE_CATEGORY, "행정학과 학사공지"),
    SOCIALSCIENCE_EDUCATION_ACADEMIC(SOCIALSCIENCE_CATEGORY, "교육학과 학사공지"),
    SOCIALSCIENCE_POLITICALSCIENCE_ACADEMIC(SOCIALSCIENCE_CATEGORY, "정치외교학과 학사공지"),
    SOCIALSCIENCE_SOCIOLOGY_ACADEMIC(SOCIALSCIENCE_CATEGORY, "사회학과 학사공지"),
    SOCIALSCIENCE_COMMUNICATION_MEDIA_ACADEMIC(SOCIALSCIENCE_CATEGORY, "미디어전공 학사공지"),
    SOCIALSCIENCE_COMMUNICATION_ADVERTISING_ACADEMIC(SOCIALSCIENCE_CATEGORY, "광고홍보학전공 학사공지"),

    // 창의공과대학
    CREATIVEENGINEERING_ACADEMIC_RSS(CREATIVEENGINEERING_CATEGORY, "창의공과대학 학사공지"),
    CREATIVEENGINEERING_MECHANICAL_ACADEMIC(CREATIVEENGINEERING_CATEGORY, "기계공학부 학사공지"),
    CREATIVEENGINEERING_ELECTRICAL_ACADEMIC_RSS(CREATIVEENGINEERING_CATEGORY, "전자공학부 학사공지"),
    CREATIVEENGINEERING_ADVANCEDMATERIALS_ACADEMIC(CREATIVEENGINEERING_CATEGORY, "신소재공학부 학사공지"),
    CREATIVEENGINEERING_CIVIL_ACADEMIC(CREATIVEENGINEERING_CATEGORY, "건설시스템공학부 학사공지"),

    // 조형대학
    DESIGN_INDUSTRIAL_ACADEMIC(DESIGN_CATEGORY, "공업디자인학과 학사공지"),
    DESIGN_VISUAL_ACADEMIC(DESIGN_CATEGORY, "시각디자인학과 학사공지"),
    DESIGN_METALWORK_ACADEMIC(DESIGN_CATEGORY, "금속공예학과 학사공지"),
    DESIGN_AUTOMOTIVE_ACADEMIC(DESIGN_CATEGORY, "자동차·운송디자인학과 학사공지"),
    DESIGN_CERAMICS_ACADEMIC(DESIGN_CATEGORY, "도자공예학과 학사공지"),

    // 사업단 및 부속기관
    LINC_ACADEMIC(OTHERS_CATEGORY, "LINC 3.0 사업단 학사공지"),
    DORMITORY_GENERAL_RSS(OTHERS_CATEGORY, "생활관 일반공지"),
    NCCOSS_GENERAL(OTHERS_CATEGORY, "차세대통신사업단 학사공지"),
    CLIMATECHANGE_ACADEMIC(OTHERS_CATEGORY, "기후변화대응사업단 학사공지"),

    // 자동차융합대학
    AUTOMOTIVEENGINEERING_ACADEMIC(AUTOMOTIVEENGINEERING_CATEGORY, "자동차융합대학 학사공지"),
    COSS_ACADEMIC(AUTOMOTIVEENGINEERING_CATEGORY, "미래자동차사업단 학사공지"),
    FUTUREMOBILITY_ACADEMIC(AUTOMOTIVEENGINEERING_CATEGORY, "미래모빌리티학과 학사공지"),

    // 법과대학
    LAW_ACADEMIC(LAW_CATEGORY, "법과대학 학사공지"),

    // 과학기술대학
    SCIENCETECHNOLOGY_CHEMISTRY_ACADEMIC(SCIENCETECHNOLOGY_CATEGORY, "응용화학부 학사공지"),
    SCIENCETECHNOLOGY_SECURITY_ACADEMIC(SCIENCETECHNOLOGY_CATEGORY, "정보보안암호수학과 학사공지"),

    // 경상대학
    ECONOMICCOMMERCE_ACADEMIC_RSS(ECONOMICCOMMERCE_CATEGORY, "경상대학 학사공지"),

    // 교양대학
    CULTURE_ACADEMIC_RSS(CULTURE_CATEGORY, "교양대학 학사공지"),

    // 교직과정부
    TEACHING_ACADEMIC_RSS(TEACHING_CATEGORY, "교직과정부 학사공지"),

    // 예술대학
    ARTS_ACADEMIC(ARTS_CATEGORY, "예술대학 학사공지"),

    // 체육대학
    PHYSICALEDUCATION_ACADEMIC(PHYSICALEDUCATION_CATEGORY, "체육대학 학사공지"),

    // 글로벌인문지역대학
    GLOBALHUMANITIES_ACADEMIC_RSS(GLOBALHUMANITIES_CATEGORY, "글로벌인문지역대학 학사공지"),
    GLOBALHUMANITIES_KOREAN_ACADEMIC_RSS(GLOBALHUMANITIES_CATEGORY, "한국어문학부 학사공지"),
    GLOBALHUMANITIES_KOREANHISTORY_ACADEMIC_RSS(GLOBALHUMANITIES_CATEGORY, "한국역사학과 학사공지"),
    GLOBALHUMANITIES_ENGLISH_ACADEMIC_RSS(GLOBALHUMANITIES_CATEGORY, "영어영문학부 학사공지"),
    GLOBALHUMANITIES_CHINESE_ACADEMIC_RSS(GLOBALHUMANITIES_CATEGORY, "중국어문학부 학사공지"),
    GLOBALHUMANITIES_EURASIAN_ACADEMIC(GLOBALHUMANITIES_CATEGORY, "러시아유라시아학과 학사공지"),

    // 외부 대회 및 공모전
    WEVITY_CONTEST(OFFCAMPUS_CONTEST_CATEGORY, "위비티 공모전 공지"),
    ONOFFMIX_CONTEST(OFFCAMPUS_CONTEST_CATEGORY, "온오프믹스 공모전 공지"),
    ONOFFMIX_HACKATHON(OFFCAMPUS_CONTEST_CATEGORY, "온오프믹스 해커톤 공지"),
    ;

    private final CategoryGroup group;
    private final String label;

    NoticeCategory(CategoryGroup group, String label) {
        this.group = group;
        this.label = label;
    }

    public CategoryGroup getGroup() {
        return group;
    }

    public String getLabel() {
        return label;
    }
}
